AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Get the wifi password
Resources:
  whatsTheWifiPassword:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: Get the wifi password
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::414993729456:role/service-role/getWifiRole'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Tags:
        'lambda-console:blueprint': alexa-skills-kit-color-expert
